set backspace=indent,eol,start
set ts=4 sw=4
set ruler
set nonu
set hls
set incsearch
set smartindent
set wildmenu
set wildmode=list:longest
set showcmd
set formatoptions=tcq
set fileformats=unix,dos
set t_Co=256
syntax on
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
set expandtab
"set noexpandtab
set clipboard=unnamed

colorscheme molokai
"colorscheme desert
let g:molokai_original = 1
let g:rehash256 = 1
" autocmd vimenter * NERDTree

augroup filetype
    au! BufRead,BufNewFile *.sproto setfiletype sproto
augroup end

" Uncomment /etc/vim/vimrc jump-last-position and plugin-indent-on

" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'

" Any valid git URL is allowed
Plug 'https://github.com/junegunn/vim-github-dashboard.git'

" Multiple Plug commands can be written in a single line using | separators
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" Using a non-master branch
"Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }

" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
" Plug 'fatih/vim-go', { 'tag': '*' }

" Plugin options
Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }

" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

"Plug 'Shougo/neocomplete.vim'

" Unmanaged plugin (manually installed and updated)
Plug '~/my-prototype-plugin'

" Initialize plugin system
call plug#end()

:nnoremap <Space>f :FZF<CR>

"let g:neocomplete#enable_at_startup = 1
"let g:neocomplete#disable_auto_complete = 1
":inoremap <expr><C-n> neocomplete#start_manual_complete()

