set backspace=indent,eol,start
set ts=4 sw=4
set ruler
set nonu
set hls
set incsearch
set smartindent
set wildmenu
set wildmode=list:longest
set showcmd
set formatoptions=tcq
set fileformats=unix,dos
set t_Co=256
syntax on
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
set expandtab
"set noexpandtab
set clipboard=unnamed

colorscheme molokai
"colorscheme desert
let g:molokai_original = 1
let g:rehash256 = 1
" autocmd vimenter * NERDTree

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

augroup filetype
    au! BufRead,BufNewFile *.sproto setfiletype sproto
augroup end

call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
call plug#end()

:nnoremap <C-P> :FZF<CR>

"let g:neocomplete#enable_at_startup = 1
"let g:neocomplete#disable_auto_complete = 1
":inoremap <expr><C-n> neocomplete#start_manual_complete()

