version: "3"

services:
    mongo:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - ./db:/data/db
        container_name: mongo_docker
        restart: always
