version: "3"

services:
	mysql:
		image: mysql:5.7
		ports:
			- 3306:3306
		volumes:
			- ./db:/var/lib/mysql
		container_name: mysql-docker
		environment:
			MYSQL_ROOT_PASSWORD: "123456a"
			MYSQL_USER: 'test'
			MYSQL_PASS: '123456'
		restart: always
