version: "3"

services:
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - ./my.cnf:/etc/my.cnf
            - ./db:/var/lib/mysql
            - ./init:/docker-entrypoint-initdb.d/
        container_name: mysql_docker
        environment:
            MYSQL_ROOT_PASSWORD: "123456a"
        restart: always
